//! Tatoeba(https://tatoeba.org)収録のロジバン実文によるコーパステスト
//!
//! 実際に母語話者・学習者が書いた文でパーサーの実用性を検証する。
//! CC BY 2.0 FR ライセンスの文を引用。

use lojban::grammar::{LojbanParser, Rule};
use pest::Parser;

/// 既知の未対応・非標準文(解析に失敗することが正)
const KNOWN_FAILURES: &[&str] = &[
    // 非標準形の借用語(zantufa でも受理されない)
    "rutrpinia",
    "rutrxanonaskuamosa",
];

#[test]
fn 既知の失敗例は拒否される() {
    for s in KNOWN_FAILURES {
        assert!(
            LojbanParser::parse(Rule::text, s).is_err(),
            "既知の失敗例が受理された: {s}"
        );
    }
}

#[test]
fn tatoeba_実文コーパス() {
    let corpus: &[&str] = &[
        ".a'onai",
        ".a'u",
        ".a'ucai",
        ".a'usai",
        ".e'enai",
        ".e'ese'a",
        ".einai",
        ".eiro'u",
        ".i'acai",
        ".i'e",
        ".i'unai",
        ".iacu'i",
        ".iepei",
        ".o'anai",
        ".o'i",
        ".oi",
        ".oicairo'aro'ero'iro'oro'ure'e",
        ".oiro'a",
        ".u'anaicai",
        ".u'ibe'u",
        ".u'unai",
        ".ua",
        ".ue",
        ".uecai",
        ".ui",
        ".uo",
        ".y",
        "a'enai",
        "a'unai",
        "a'unaicai",
        "be'e",
        "be'u",
        "bredi",
        "ca'o",
        "carvi",
        "cidja",
        "cizra",
        "co'o",
        "di'ai",
        "dormijysai",
        "drani",
        "fau'u",
        "fe'o",
        "fenki",
        "fi'i",
        "fonxa",
        "frili",
        "ge'e",
        "i'e",
        "iebu'o",
        "ienaisai",
        "iesai",
        "jaurcarvi",
        "je'upei",
        "ju'oinai",
        "ju'oipei",
        "karce",
        "ki'ecai",
        "kukte",
        "la'anai",
        "li'a",
        "nandu",
        "nei",
        "ni'au",
        "nonselsmu",
        "nu'e",
        "nu'epei",
        "o'i",
        "oi",
        "pei",
        "peizo'onai",
        "prane",
        "racli",
        "rigni",
        "rolcumja'e",
        "rutrxanana",
        "si'ercarvi",
        "simsa",
        "smucau",
        "ta'onai",
        "tolzdi",
        "u'esai",
        "u'usai",
        "uanaisai",
        "ue'ipei",
        "uidai",
        "uidaisai",
        "uisai",
        "uusai",
        "vecnu",
        "vi'osai",
        "vindu",
        "xamgu",
        "zabna",
        "zo'o",
        "zo'onai",
        "zu'i",
        ".audaipei klama",
        ".e'unai gerku",
        ".u'e barda gerku",
        ".u'e melbi",
        "ausai viska ra",
        "da prami rode",
        "do djica ma",
        "do ma tavla",
        "do melbi",
        "do na gerku",
        "do na viska",
        "do prenu",
        "klama ma",
        "ko co'a klama",
        "ko klama",
        "ko na tavla",
        "ko na viska",
        "ko tavla",
        "ko viska",
        "ko viska ta",
        "ko'a djica loka snada",
        "ko'a melbi",
        "ko'a na djica",
        "ko'a prami mi",
        "ko'a prenu",
        "ko'a venfu djica",
        "ko'a xamgu tavla",
        "ma klama ma",
        "ma nu prami",
        "ma prami ma",
        "ma prenu",
        "ma tavla",
        "melbi dinju",
        "melbi xadni",
        "mi djica lo xagrai",
        "mi gerku",
        "mi melbi",
        "mi na gerku",
        "mi prami mi",
        "mi prami ra",
        "mi prami vo'a",
        "mi pu viska",
        "mi se prami",
        "mi tavla ko",
        "mi venfu djica",
        "mi viska",
        "mi'o prenu",
        "mo nu tavla",
        "mutce melbi",
        "o'i fengu gerku",
        "so'iroi tavla",
        "ti gerku",
        "ti gerku ma",
        "ti melbi",
        "ti mo gerku",
        "tu cladu tavla",
        "tu xamgu tavla",
        "vrude prenu",
        "xendo prenu",
        "xo prenu",
        "xu do djica",
        "xu ti gerku",
        "za'u ko'a prenu",
    ];
    let mut failures = Vec::new();
    for s in corpus {
        if let Err(e) = lojban::parse(s) {
            failures.push(format!("{s} :: {}", e.variant.message()));
        }
    }
    assert!(
        failures.is_empty(),
        "解析失敗 {}件:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

/// CLL 風の厳選例文(各構文のカバレッジ強化)
const CURATED: &[&str] = &[
    "le nu do klama cu mlatu",
    "mi djica lo nu do gleki",
    "le prenu poi tavla cu melbi",
    "le du'u mi klama cu melbi",
    "le se du'u mi klama cu melbi",
    "mi me le mlatu",
    "la alis. cu me mi",
    "lo smuci ku pe mi",
    "le gerku pe lo pendo cu batci",
    "fa mi tavla fe do",
    "fi le zdani fe do fa mi klama",
    "sei mi gleki do klama",
    "ta'e mi cadzu",
    "ru'i le mlatu cu bajra",
    "ka'e do kakne",
    "mi ca ba klama",
    "do pu ca'o tavla mi",
    "mi ba zi vitke do",
    "vi le zdani cu mlatu",
    "coi doi pendo",
    "ki'e la alis.",
    "je'e doi dirba",
    "mu'o ge'e coi",
    "pe'u do cusku zo'e",
    "fi'i do klama le zdani",
    "xu do su'a djica",
    "ie mi fanva",
    "ue le ci gerku cu melbi",
    "uu do bilma",
    "ju'o mi kenin",
    "le mlatu ku cu cadzu",
    "zo'e cu tavla zo'e",
    "ma tavla do",
    "do viska ma",
    "mi dunda ti ma",
    "le re mlatu cu melbi",
    "re lo ci gerku cu batci",
    "pa prenu cu klama",
    "ro da prami ro de",
    "mi nelci le nu sipna",
    "le ka melbi cu se stidi mi",
    "le cmalu nixli cu melbi",
    "melbi cmalu nixli ckule",
    "mi viska le cmalu nixli",
    "ta cu mlatu",
    "ti ta mi",
    "mi cusku zo coi",
    "do pu cusku lu mi klama lihu",
    "le gerku poi cadzu ku'o cu batci",
    "lu mi klama li'u",
    "ni'o mi viska do",
    "mi e do klama",
    "ta melbi je cmalu zdani",
    "ge mi gleki gi do bilma",
    "mi tavla do bau la lojban.",
    "ta to'e melbi",
    "li re su'i re du li vo",
    "mi dunda li pa pi'i ci do",
    "mi viska le re su'i ci gerku",
    "mi cusku zoi .ky. hello world .ky.",
    "li xy su'i re du li vo",
    "mi bu prami do",
    "mi gu'e klama gi cadzu",
    // v0.28: Tatoeba 再取得分(v0.14 分との重複は除外)
    "ju'oipei ...",
    "ko'a cagypre",
    "ko'a ci'ernunbi'opre",
    "ko'a blanu",
    "mi'e .eryr",
    "do xajmi",
    "ko gunka",
    "ko zgipli",
    "ko bredi",
    ".i je'e",
    "mi trucu'upre",
    "ko zajba",
    "pu cipra",
    "laldo nuzba",
    "doi mabla",
    "ko kalri",
    "mi citka",
    "li'asai toldra",
    "ca si'ercarvi",
    "ma tcika",
    "ko'a bebna",
    "uo ki'e",
    "pu faursutrytce",
    "na jetnu",
    "dukse kargu",
    "mi laldo",
    "ti cartu",
    "cizra je'upei",
    "ko'a blabi",
    "pu snuti",
    "mi zifre",
    "ma morji",
    "ma nalzva",
    "mi'e .xacimotos.",
    "mi plana",
    "cai spaji",
    "na speni",
    "do malcrexalbo",
    "mi dzukla",
    ".i'enai ctuci'e",
    ".a'usai lisri",
    "ca'o banro",
    "ko'a fange",
    "mi sipta'i",
    "ko sidju",
    "do ticysku",
    ".i mipri",
    "mi glabi'a",
    "ko pensi",
    "ju'i jbopli",
    "jatna mi",
    "ra gleki",
    "cliva ma",
    "mi tadni",
    "mi tugni",
    "mi'a tugni",
    ".ie nai",
    "mi cortu",
    "pe'i do vudvri",
    "ti na prali",
    // v0.38: Tatoeba 再取得分(v0.14 分との重複は除外)
    "do claninmu",
    "ma djacu",
    "ma bangidu'o",
    "ko krixa",
    "ko cisma",
    "nicte coi",
    "ko surla",
    ".o'o cu'i",
    "mi sigva'u",
    "xu cizra",
    ".ui pei",
    "e'anai nerkla",
    "mi virnu",
    "janta pe'u",
    "na'e selspaji",
    "ta'e cando",
    "na'e cnino",
    "do cizra",
    "na sedyta'u",
    "fadni selgu'a",
    "tsali ca'erbi'e",
    "pruspe do",
    "dukse lerci",
    "mi stagycti",
    "puco'a sanga",
    "ca'o sazysti",
    "mi muspre",
    "mi mulgau",
    "mutce tatpi",
    "no da cevni",
    // v0.50: Tatoeba 定期再検証分
    "ko'a li'urxa'u",
    "mi xebro",
    "ko bajli'a",
    "mi'a ninmu",
    "ki'a nai",
    "ru'a na'ipei",
    "xu crori'a",
    "sinxa ma",
    "pu cizra",
    "do verba",
    ".u'u kumclu",
    "mi'o dansu",
    "cabyfau xu",
    "djusku ma",
    "ma'a prenu",
    "ko nalfengu",
    "dei jufra",
    "ra sa'acre",
    "ma'a gleki",
    "do ctuca",
    // v0.56: Tatoeba 定期再検証分
    "mi'o dzejdasra",
    "mi no'ordo",
    "ko vaxtisna",
    "mi kujmikce",
    "xu banli",
    "ko cikna",
    "u'e snime",
    "ne'i manku",
    "da'i .ie",
    "do ricfu",
    "do ruble",
    "mi'a sidju",
    "ko jarco",
    "morsi vindu",
    "xautce vacysai",
    "ko'a tolsanji",
    "mi muslo",
    "mi'e .farcad.",
    "mi'a gleki",
    "pu nicte",
];

#[test]
fn 厳選例文コーパス() {
    let mut failures = Vec::new();
    for s in CURATED {
        if let Err(e) = lojban::parse(s) {
            failures.push(format!("{s} :: {}", e.variant.message()));
        }
    }
    assert!(
        failures.is_empty(),
        "解析失敗 {}件:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
